### ISSUE TITLE
ios 13 not working

### ISSUE THREAD

**Issue by raf1dd** [gilesgc/CCCalc#4]
Hey so on ios 13 with Checkra1n jailbreak it sends me to safemode when i try to 3d touch the calculator from cc

**Comment by NineBallAYAYA** [comment]
fairly good for a quick respring.... but yea.

**Comment by gilesgc** [comment]
Fixed in latest update

**Comment by raf1dd** [comment]
> Fixed in latest update

Working just fine thanks a lot
