### ISSUE TITLE
Not working on lock screen 

### ISSUE THREAD

**Issue by tato20** [gilesgc/CCCalc#5]
As title. It’s not showing the keyboard when screen is locked. Still functioning but it’s inconvenient. 
![A4B2E5A1-B829-4126-B24B-3E7F247EFB17](https://user-images.githubusercontent.com/61010601/74430717-73b4a400-4e2b-11ea-8d78-2c9cb013c054.png)

**Comment by gilesgc** [comment]
Thanks, fixed in latest version 1.2.1
