### ISSUE TITLE
1.2.0 doesn’t work on iPhoneSE2 13.5

### ISSUE THREAD

**Issue by Halo-Michael** [gilesgc/CCCalc#7]
![D9248AB8-503B-4C5B-8819-87603E08FD3D](https://user-images.githubusercontent.com/45062120/87391546-86e7bd80-c5dd-11ea-8982-7b7aa496cceb.png)

**Comment by Halo-Michael** [comment]
Also got the same screen on iPhone6s+ 13.2.3 and iPhone7 13.4.1.

**Comment by IvanKulagin** [comment]
Same thing on iPhone 11 Pro Max 13.5

**Comment by Halo-Michael** [comment]
Seems fixed in 1.2.1

**Comment by gilesgc** [comment]
1.2.1 just released, it's fixed now
